### ISSUE TITLE
Support targeting solution filters

### ISSUE THREAD

**Issue by rabuckley** [seblj/roslyn.nvim#125]
I've got a POC in my [branch](https://github.com/rabuckley/roslyn.nvim/tree/solution-filters) but with some breaking changes.

Happy to open a PR if wanted.

**Comment by seblj** [comment]
Thanks! I took a quick look at it, and I think I am willing to support this. However, I think I want to revert some of the breaking changes...

I think, for now at least, we should keep the api.lua the same, and not rename anything there. I think we can just create the new methods in utils.lua.

I don't have the best documentation, but I look at the methods in utils.lua as sort of "private" even though they are exposed, and the ones in api as something other plugins or someone could use int their config.

A couple of other things: I think we should try and combine some of the vim.fs.root and vim.fs.find methods in the utils.root method. I have gotten a couple of issues earlier about performance when finding the solution file, and this adds even more filesystem searching.

Otherwise, I think it looks good. I think I like the naming change of the config option for `ignore_target` and `choose_target`. I have actually been considering adding the .csproj files it finds to the vim.ui.select list, so that it is possible to only load a single project. Then target as a name fits better. I think however we should accept the old names for now and issue a notify warning about those options being deprecated if they are used, and then I will remove them at a later time
