### ISSUE TITLE
Diagnostic error does not disappear when error gets resolved until you modify anything

### ISSUE THREAD

**Issue by marcinjahn** [seblj/roslyn.nvim#13]
I noticed this one scenario where LSP error diagnostic does not disappear from a line of code even after the issue gets corrected.
Here's the scenario:

I have two files:

```cs
// IService.cs

public interface IService
{
   void DoSomething(int someInt);
}
```

```cs
// Service.cs

public class Service : IServce
{
  void DoSomething(int someInt) {}
}
```

Now, if I decide to modify the `DoSomething` method, I need to modify both of my files. Let's say I want to remove the `someInt` parameter entirely.

One way to do that is:

1. Go to interface file, remove the parameter
2. Go back to class file, error will not appear, **until you start to modify the file somehow**
3. Fix the error in the class file, error disappears.

Is this something that Roslyn just doesn't properly implement?

**Comment by seblj** [comment]
Hmm, is the behaviour different in vscode?

**Comment by iamim** [comment]
I reminds me of this issue in svelte LSP: https://github.com/sveltejs/language-tools/issues/2008#issuecomment-2148860446

**Comment by seblj** [comment]
Okay, so I did some quick investigation. I think the reason this happens is because it looks like roslyn is only implementing pull diagnostics and not push diagnostics. And neovim is not pulling "often enough". I am not sure if there is anything in the spec about how often a client should pull diagnostics from the server. I noticed that there is a difference in vscode and neovim, so it might be that vscode is pulling diagnostics more often than neovim. Or it could also be that I have missed something about how diagnostics is handled in roslyn.

However, I have this very hacky snippet that you could iterate on and pull//refresh diagnostics as often as you would like:

```lua
vim.api.nvim_create_autocmd({ "InsertLeave" }, {
    pattern = "*",
    callback = function()
        local clients = vim.lsp.get_clients({ name = "roslyn" })
        if not clients or #clients == 0 then
            return
        end

        local buffers = vim.lsp.get_buffers_by_client_id(clients[1].id)
        for _, buf in ipairs(buffers) do
            vim.lsp.util._refresh("textDocument/diagnostic", { bufnr = buf })
        end
    end,
})
```

This is pulling diagnostics on every `InsertLeave`. So you could add your own events there. It seems a bit hacky though, and I don't think I want to do some special handling for this in the plugin itself😅

**Comment by marcinjahn** [comment]
Interesting. How do you sniff the communication between neovim and roslyn? (or vscode and roslyn)

**Comment by seblj** [comment]
Either through `:lua vim.lsp.set_log_level(0)` and then do something, and then check and analyze the logs with `:LspLog`. Or in this case I actually just tried to look at the source code for roslyn. I just searched for diagnostics or something, and then just looked through a couple of references which it could potentially be, and then I saw some comments about them supporting pull diagnostics, and then I couldn't find anything else about diagnostics🤷‍♂️

**Comment by seblj** [comment]
I think this can be closed here, as there is not much more to be done from my side. This either needs a change in neovim core, or roslyn implementing push diagnostics or something
