### ISSUE TITLE
Support for full source decompilation

### ISSUE THREAD

**Issue by BurkeStrang** [seblj/roslyn.nvim#19]
Could we add support for full source decompilation? So you can view more than just the interface of libraries etc. Or add the ability to override the handlers? Something like this I believe would do that. https://github.com/Decodetalkers/csharpls-extended-lsp.nvim?tab=readme-ov-file

**Comment by seblj** [comment]
I admit that this would be really nice. I need to see how vscode does this, because if the current way is the same, then I don't think I want to implement this in this repo. I might be wrong here, but I feel that this really should be handled by the server itself. However, I will absolutely add option to override handlers. I cannot guarantee I am able to do it straight away since I am a bit absent because of holiday.

**Comment by seblj** [comment]
The latest commit allows for overriding handlers. They can be passed as normal to the `config` option in the setup method. These will be merged with the default ones I am providing, and it will prefer the users handler if you implement the same handler that I have already implemented by default here

**Comment by franroa** [comment]
This sounds amazing!
Does anyone know the config we need to pass for fully decompilation support?

**Comment by marcinjahn** [comment]
The LSP would have to support decompilation in the first place, and it seems Roslyn does not support that. https://github.com/dotnet/vscode-csharp/issues/5761

**Comment by ADIX7** [comment]
I'm using `4.12.0-1.24365.10` version of the language server and with `vim.lsp.buf.definition` it does open the decompiled source by default.

This is the settings, but it is `true` by default, so no need to set this, only if you want to turn it off.
` ``
["navigation"] = {
    ["dotnet_navigate_to_decompiled_sources"] = true/false,
},
```

The only problem is that you can't navigate further, although VSCode can't do that either.

**Comment by seblj** [comment]
I think I'll close this issue, as I see this as a server limitation. I have modified the code a bit so that it will attach to the decompiled files with the already selected solution.

From minimal testing, some navigation is working, but not everything. It seems like this is similar to how it works in vscode atm
