### ISSUE TITLE
Implement changes from other forks

### ISSUE THREAD

**Issue by franroa** [seblj/roslyn.nvim#21]
Hi, here a couple of interesting things that other forks have implemented on the repo:
https://github.com/jmederosalvarado/roslyn.nvim/compare/main...StefanFanaru:roslyn.nvim:main
https://github.com/jmederosalvarado/roslyn.nvim/compare/main...neubaner:roslyn.nvim:main
https://github.com/jmederosalvarado/roslyn.nvim/compare/main...krsma33:roslyn.nvim:main
https://github.com/jmederosalvarado/roslyn.nvim/compare/main...adorno-dev:roslyn.nvim:main

I think it could be really good to gather everything in one place

**Comment by seblj** [comment]
I need to look more closely on this later, because I have already implemented some of those things.

**Comment by seblj** [comment]
Okay, so I sent a PR to `nvim-treesitter` to fix hover to have treesitter highlighting. I also updated the README to how you can pass in some settings to the server. I will need to look into them at a later time to see if I maybe should add some of them by default. For example inlay hints which I have an example for in the README.

Otherwise, there is one handler that is implemented in one of the forks which I have not implemented yet. However, I have another issue open on that, and I will see what the proper way to implement that handler is.

Most of the other things is already supperted and implemented in this plugin.

The one thing that I haven't done yet is add a command to fix all usings. However, I don't really know if I want this in the plugin. It is already a part of the code actions suggestion if you use that, and it seems unnecessary to pollute the command space for this when one can easily do something like `gg` to go to top of document, `gra` to get code actions, and then select the correct one, and then `<C-o`> to get back

**Comment by franroa** [comment]
That sounds awesome, thanks!
The change with the fix usings is a nice to have to be honest, However is cool to have the same keymaps as with other languages.
In any case, thank you for your great job, this is one of my favourites plugins in neovim right now

**Comment by seblj** [comment]
Okay, the PR to nvim-treesitter didn't go through, but I added a fix to it here then. The things missing are now the handler I was talking about, and the user command to remove unnecessary using directives.

I have another issue for the handler which I want to get to soon. I hope I will be able to get to it at least before the end of next week. I am still on vacation this week, so I am not as active as normal.

I prefer the user command to not be in this repo as I said. It can instead easily be implemented by user with something like this:

```lua
vim.api.nvim_create_user_command("CSFixUsings", function()
    local bufnr = vim.api.nvim_get_current_buf()

    local clients = vim.lsp.get_clients({ name = "roslyn" })
    if not clients or vim.tbl_isempty(clients) then
        vim.notify("Couldn't find client", vim.log.levels.ERROR, { title = "Roslyn" })
        return
    end

    local client = clients[1]
    local action = {
        kind = "quickfix",
        data = {
            CustomTags = { "RemoveUnnecessaryImports" },
            TextDocument = { uri = vim.uri_from_bufnr(bufnr) },
            CodeActionPath = { "Remove unnecessary usings" },
            Range = {
                ["start"] = { line = 0, character = 0 },
                ["end"] = { line = 0, character = 0 },
            },
            UniqueIdentifier = "Remove unnecessary usings",
        },
    }

    client.request("codeAction/resolve", action, function(err, resolved_action)
        if err then
            vim.notify("Fix using directives failed", vim.log.levels.ERROR, { title = "Roslyn" })
            return
        end
        vim.lsp.util.apply_workspace_edit(resolved_action.edit, client.offset_encoding)
    end)
end, { desc = "Remove unnecessary using directives" })
```

**Comment by marcinjahn** [comment]
Maybe it'd make sense to add some kind of recipes section to this repo? As a wiki, or some separate markdown?

**Comment by seblj** [comment]
Good idea, I can create a wiki and add this snippet there

**Comment by franroa** [comment]
That sounds really good.
Thank you for your efforts!
