### ISSUE TITLE
Incredibly slow to enter/exit c# buffers in large projects

### ISSUE THREAD

**Issue by svermeulen** [seblj/roslyn.nvim#45]
In my project, I measured this to be around 200 ms which is very noticable.

My guess is that this is because in the get_solution_files method of "slnutils.lua", it's doing vim.fs.find under the root, which is recursive by default, whereas it should just scan direct children (either this or at least cache this calculation in a buffer local variable)

**Comment by seblj** [comment]
Try to see if it can be because of filewatching. I have a config option for that explained in the readme

**Comment by svermeulen** [comment]
I tried setting filewatching to false and same issue

**Comment by seblj** [comment]
It sees weird that it is slow to exit because of that? Could you try to edit the code and just hardcode the solution file? That way we can be sure that it is because of vim.fs.root

**Comment by svermeulen** [comment]
You're right, it's only on enter.  Just seemed that way when going from a c# file to another c# file.  But going to text file doesn't have this problem.

I can confirm that it's the call to vim.fs.find (not vim.fs.root) that takes around 150 ms

**Comment by seblj** [comment]
Hmm, specifically, is it only `get_solution_files` that is slow? Not `try_get_csproj_files`?

**Comment by filipesilva-l** [comment]
Hi,

I can confirm that the issue began after my most recent update. I tested it, and the slowdown seems to have originated from this [commit](https://github.com/seblj/roslyn.nvim/commit/a455ae6e13576fa58838df80764b20439a41b806).

**Comment by seblj** [comment]
Hmm okay. It is a bit annoying how to start the server, and that it is different for solution and project. I have 3 different cases that I want to support:

- If you open neovim inside a subfolder of where a solution is, I want it to be possible to only work in that "project"
- If the firsy is not true, and we find a solution file, use that
- If neither of the ones above are found, then see if we find a csproj file.

Currently it is doing that, but there might a better/more efficient way. I need to try to think of something clever. I could possible add some async to not block the editor, but I prefer not to, since it complicates it a little bit, and there is no easy way to do it without a lot of boilerplate in core

**Comment by filipesilva-l** [comment]
After further investigation, it turns out that the real issue lies in the get_solution_files function.

The function scans every file in all directories within the root, which is a highly resource-intensive operation for large projects. In my case, I noticed that `vim.fs.find` was unnecessarily searching through directories like `.git`, `bin`, and `obj`. I checked the [vim.fs.find implementation](https://github.com/neovim/neovim/blob/8a2aec99748229ad9d1e12c1cbc0768d063e8eed/runtime/lua/vim/fs.lua#L222) and attempted to exclude these unnecessary directories, but the sheer number of files still slowed down my editor.

I see two possible solutions:

- Perform a one-time search for solution files and cache the results based on the root directory.
- Limit the search to directories between the current buffer and the root, instead of scanning everything.

Since I don’t work with sub-solutions often, I’m not sure which approach is best here.

**Comment by filipesilva-l** [comment]
Sorry, I tested adding a cache to the `get_solution_files` and the slowness still persists. It looks like `try_get_csproj_files` is suffering from the same problem of analyzing every file in every directory inside root.

**Comment by seblj** [comment]
Yeah I know. I need some time to figure out what I should do here to make it faster. In the meantime if it is very annoying, you could pin the version to an older commit. Feel free to share if you have an interesting way to fix this. Otherwise, I will also be updating here when I have something new. I'll try to work on it early this week, but I don't know if I have time tomorrow

**Comment by filipesilva-l** [comment]
What is the benefit of prefering the .csproj file if we open neovim in the directory of the project?

I ask this because I just tested it and when I open inside the project folder, I cannot access the implementation of types declared in another .csproj even though it's in the same solution.

A possible solution would be also caching the search of this search by the current working directory, but I don't know the drawbacks of that.

**Comment by filipesilva-l** [comment]
what do you think about using a function like this to search for .csproj and .sln files?

```lua
--- Recursively searches for files with a specific extension within a directory range.
--- The search starts at the 'from' directory and continues until the 'to' directory.
--- Only files matching the provided extension are returned.
---
--- @param from string The starting directory path for the search.
--- @param to string? The ending directory path to stop the search. (Cannot contain '/' in the end)
--- @param extension string The file extension to look for (e.g., ".sln").
---
--- @return string[] List of file paths that match the specified extension.
function find_files_with_extension(from, to, extension)
    local matches = {}

    for dir in vim.fs.parents(from) do
        if dir == to then
            break
        end

        for entry, type in vim.fs.dir(dir) do
            if type == "file" and vim.endswith(entry, extension) then
                matches[#matches + 1] = vim.fs.normalize(vim.fs.joinpath(dir, entry))
            end
        end
    end

    return matches
end
```

This approach would significantly optimize the search by limiting it to files within the path from the current buffer to the root or the current working directory.

If the broader search is still needed, we could make the smaller, more efficient search the default, with the slower, more comprehensive search as an opt-in option.

**Comment by seblj** [comment]
I was playing around with something like this myself for a couple of minutes last night, but I got too tired before I could get anywhere, so initially I think it could make sense.

I have one corner case in a personal project of mine where I would like to choose a sln file that would need a "broader" search, but maybe I could change the `choose_sln` slightly🤔

For me at least, we have a couple of standalone projects that are not part of the solution, and I would then like the option to only open that project. I don't need it to analyze everything then, so that is the reason I want it to prefer the csproj if I open neovim inside a folder with csproj
