### ISSUE TITLE
Should server update (be "aware" of) other files buffer changes ? 

### ISSUE THREAD

**Issue by konstantin-mohin** [seblj/roslyn.nvim#53]
when changing an Interface I still see an old signature of it on other files as a result errors by not implementing the Interface, should it auto update once code changes ? 
am using default config with `filewatching = false` 
have to close and open nvim.

**Comment by seblj** [comment]
`filewatching = false` is not the default value

**Comment by konstantin-mohin** [comment]
confirming, it does refresh and signature changes.
so you're saying you do it each time manually, I wonder how vs code resolves this... 

thanks

**Comment by seblj** [comment]
There is probably some LSP handler you can call in an autocmd or something, but I am not entirely sure which one it is.

Regardless, this is probably more related to how neovim implements the protocol and not this plugin.

I am mostly just wrapping the start of the server since the server is not compliant with the spec, and also just implemented s couple of custom handlers specific for the server to make it a bit better
