### ISSUE TITLE
Is there anyway to refresh Lsp?

### ISSUE THREAD

**Issue by JustBarnt** [seblj/roslyn.nvim#64]
I use neovim as my editor, but a lot of my C#/dotnet work is done with winforms, so I use Visual Studio purely for its winforms designer. But if make any changes there the roslyn lsp in neovim is unaware. So I have to stop the Lsp manually. Close the file then reopen it. 

I was curious if it would be possible to add a custom command that can be ran to do this? running `LspStop` and 'LspStart' doesn't seem to do anything either.

**Comment by seblj** [comment]
Yeah that is kind of annoying, because it isn't registered in nvim-lspconfig, it doesn't really know of roslyn. I know there is plans to upstream some of this, but it doesn't seem like it is ready in the near future.

I have actually thought of implementing this as I have had a request for the same thing from one colleague. I will look into implementing it👍

**Comment by JustBarnt** [comment]
@seblj Awesome! Well, I look forward to it if you get the chance! This plugin has made working with C# so easy, so I really appreciate the work put into it!

**Comment by JustBarnt** [comment]
@seblj Yeah this is perfect! Thank you!
