### ISSUE TITLE
Adding server download and updating to the plugin

### ISSUE THREAD

**Issue by ChuufMaster** [seblj/roslyn.nvim#78]
# Adding server download to the Main plugin

I've been working on an update to this plugin that will allow the language server to be downloaded through the plugin instead of through mason or doing it manually.

I thought some people would be interested and I will open a PR soon once I am happy with the state of changes I have made.

**Comment by seblj** [comment]
I have been quite reluctant to adding that to this plugin previously...

I must say that I am starting to become a little bit more open to it.

I took a quick peek over what you have done so far, and it seems like it has potential.

What I would want from this, is that it "just works" on all platforms. That includes windows. Even though I am not using windows myself, it should be supported.

Also, I will probably not give too much love to the installation part myself, and hope that you and potentially others could help out if it stops working at some point. That is one of the reasons I did not want to include it from the start. Now the plugin has become more popular than I thought it would, and I see the need for it. And I also see potential in contributions for this

So, I think if we can get a clean solution that "just works", I would be open to include it! Looking forward to seeing how it turns out

**Comment by ChuufMaster** [comment]
Yea I think it should be something that "just works". That's why I have tried to stick to using the builtin methods for nvim as much as possible but that is proving difficult. The only thing I can see being a problem is that windows doesn't have a version of `unzip` which I can reliably use from the shell and I can't test it on windows because I don't use windows.

**Comment by seblj** [comment]
Hmm, I have an alternative approach which I maybe think that I prefer... There is someone who created a custom mason registry for roslyn in the wait for it to be merged into the main one. That doesn't really seem to be happening as the author of mason had some concerns for that.

I was maybe thinking more something like this: https://github.com/seblj/roslyn.nvim/pull/80

It seems to work pretty ok for me at least. What do you think?

**Comment by ChuufMaster** [comment]
This is honestly a better and more maintainable solution, I am happy to help in any way possible even if its not by contributing code directly.

**Comment by seblj** [comment]
Thank you!
